// libs/admin-dashboard/core/domain/src/lib/nav.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router';
import Toolbar from 'primevue/toolbar';
import Button from 'primevue/button';
import Divider from 'primevue/divider';
import { useCoreStore } from '@e-commerce/admin-dashboard/core/data-access';
import { useAuthService } from '@e-commerce/admin-dashboard/auth/api';

const store = useCoreStore();
const authService = useAuthService();
</script>

<template>
  <div
    class="w-full flex items-center sticky bottom-0 left-0 right-0 xl:hidden"
  >
    <Toolbar class="bg-content-background border-none w-full">
      <template #center>
        <div
          class="mx-auto max-w-lg w-full flex items-center justify-evenly gap-4"
        >
          <Button
            size="large"
            text
            icon="pi pi-bars"
            class="text-muted-color h-10 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
          />
          <RouterLink
            to="/books/list"
            active-class="bg-surface-50 dark:bg-surface-800 rounded-base"
            class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700 cursorpointer"
          >
            <i class="pi pi-book"></i>
          </RouterLink>
          <RouterLink
            to="/"
            active-class="bg-surface-50 dark:bg-surface-800 rounded-base"
            class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700 cursorpointer"
          >
            <i class="pi pi-home"></i>
          </RouterLink>

          <RouterLink
            to="/account"
            active-class="bg-surface-50 dark:bg-surface-800 rounded-base"
            class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700 cursorpointer"
          >
            <i class="pi pi-user"></i>
          </RouterLink>
        </div>
      </template>
    </Toolbar>
  </div>

  <div class="max-w-80">
    <aside
      :class="[
        store.isExpanded ? 'w-80' : 'w-14',
        'transition-[width] duration-300 ease-in-out hidden justify-between gap-4 xl:h-content px-2 py-4 bg-content-background xl:sticky z-[501] top-4 flex-col rounded-base xl:flex',
      ]"
    >
      <nav class="h-content flex flex-col justify-between">
        <div class="flex flex-col">
          <div class="h-9 flex items-center justify-center">
            <RouterLink
              to="/"
              v-if="store.shouldLabelBeShowed"
              class="items-center justify-center"
            >
              <span class="font-bold text-primary">Story</span>
              <span class="uppercase text-muted-color">Stash</span>
            </RouterLink>

            <RouterLink
              v-if="!store.shouldLabelBeShowed"
              to="/"
              active-class="bg-surface-50 dark:bg-surface-800 rounded-base"
              class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
            >
              <i class="pi pi-home"></i>
            </RouterLink>
          </div>
          <Divider />
          <ul class="flex flex-col">
            <RouterLink
              to="/books"
              activeClass="bg-surface-50 dark:bg-surface-800"
              class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700 cursorpointer"
            >
              <i class="pi pi-book"></i>
              <span v-if="store.isExpanded">Books</span>
            </RouterLink>
          </ul>
        </div>

        <div class="flex flex-col gap-2">
          <button
            class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
            @click="authService.logout"
          >
            <i class="pi pi-sign-out"></i>
            <span v-if="store.isExpanded">Log out</span>
          </button>
          <Divider />
          <button
            class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
            @click="store.toggleTheme"
          >
            <i v-if="store.isDark" class="pi pi-moon"></i>
            <i v-if="!store.isDark" class="pi pi-sun"></i>
            <span v-if="store.isExpanded">
              {{ store.isDark ? 'Dark' : 'Light' }}
            </span>
          </button>
          <button
            class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
            @click="store.toggleExpandCollapse"
          >
            <i v-if="store.isExpanded" class="pi pi-arrow-left"></i>
            <i v-if="!store.isExpanded" class="pi pi-arrow-right"></i>
            <span>Collapse</span>
          </button>
        </div>
      </nav>
    </aside>
  </div>
</template>

// libs/delivery-manager/core/feature/nav/src/lib/nav.tsx
import { Link, NavLink } from 'react-router-dom';
import { useRef, useState } from 'react';
import { useAuthApi } from '@e-commerce/delivery-manager/auth/api';
import { Toast } from 'primereact/toast';
import { useCoreStore } from '@e-commerce/delivery-manager/core/data-access';

export function Nav() {
  const [isExpanded, setIsExpanded] = useState(true);
  const [isLabelShowed, setIsLabelShowed] = useState(true);
  const timerRef = useRef<NodeJS.Timeout | null>(null);
  const { logout } = useAuthApi();
  const toast = useRef<Toast | null>(null);
  const { isDark, setTheme } = useCoreStore();

  function expandCollapse() {
    setIsExpanded((isExpanded) => !isExpanded);

    if (timerRef.current) clearTimeout(timerRef.current);

    timerRef.current = setTimeout(
      () => {
        setIsLabelShowed(!isExpanded);
      },
      isExpanded ? 0 : 150,
    );
  }

  function onLogout() {
    logout();

    toast.current?.show({
      detail: 'You have been logged out',
      summary: 'Success',
      severity: 'success',
    });
  }

  return (
    <>
      <Toast ref={toast} />

      <div className="dock dock-md bg-base-300 sticky bottom-0 xl:hidden">
        <NavLink
          to="/"
          className={({ isActive }) => (isActive ? 'dock-active' : '')}
        >
          <span className="pi pi-home"></span>
          <span className="dock-label">Home</span>
        </NavLink>

        <NavLink
          to="/orders"
          className={({ isActive }) => (isActive ? 'dock-active' : '')}
        >
          <span className="pi pi-list"></span>
          <span className="dock-label">Orders</span>
        </NavLink>

        <button onClick={onLogout}>
          <span className="pi pi-sign-out"></span>
          <span className="dock-label">Log out</span>
        </button>
      </div>

      <div className="max-w-80">
        <div
          className={
            'transition-[width] duration-300 ease-in-out hidden justify-between gap-4 xl:h-content px-2 py-4 bg-base-300 xl:sticky z-[501] top-4 flex-col rounded-base xl:flex ' +
            (isExpanded ? 'w-80' : 'w-14')
          }
        >
          <nav className="h-content flex flex-col justify-between">
            <div className="flex flex-col">
              <div className="h-9 flex items-center justify-center">
                {isLabelShowed && (
                  <Link to="/" className="items-center justify-center">
                    <span className="font-bold text-primary">Story</span>
                    <span className="uppercase text-muted-color">Stash</span>
                  </Link>
                )}

                {!isLabelShowed && (
                  <Link to="/" className="px-3 h-10 flex items-center gap-4">
                    <i className="pi pi-home"></i>
                  </Link>
                )}
              </div>
              <div className="bg-primary w-full h-[1px] my-4"></div>
              <ul className="flex flex-col">
                <Link
                  to="/orders/list"
                  className="px-3 h-10 flex items-center gap-4"
                >
                  <i className="pi pi-list"></i>
                  {isLabelShowed && <span>Orders</span>}
                </Link>
              </ul>
            </div>

            <div className="flex flex-col gap-2">
              <button
                className="px-3 h-10 flex items-center gap-4"
                onClick={onLogout}
              >
                <i className="pi pi-sign-out"></i>
                {isLabelShowed && <span>Log out</span>}
              </button>
              <div className="bg-primary w-full h-[1px] my-4"></div>
              <button
                className="px-3 h-10 flex items-center gap-4"
                onClick={expandCollapse}
              >
                {isLabelShowed && (
                  <>
                    <i className="pi pi-arrow-left"></i>
                    <span>Collapse</span>
                  </>
                )}
                {!isLabelShowed && <i className="pi pi-arrow-right"></i>}
              </button>
            </div>
          </nav>
        </div>
      </div>
    </>
  );
}

export default Nav;
