// apps/admin-dashboard/src/app/App.vue
<script setup lang="ts">
import { RouterView } from 'vue-router';
import { Nav } from '@e-commerce/admin-dashboard/core/domain';
import Toast from 'primevue/toast';
</script>

<template>
  <Toast />
  <div
    class="flex flex-col-reverse w-full h-svh xl:flex-row xl:p-gap xl:min-h-svh xl:h-full"
  >
    <Nav />
    <div
      class="w-full h-full overflow-y-auto p-4 xl:pl-gap xl:p-0 xl:overflow-y-visible"
    >
      <RouterView />
    </div>
  </div>
</template>

// apps/client-web/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { NavComponent } from './components/nav/nav.component';

@Component({
  standalone: true,
  imports: [RouterOutlet, NavComponent],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {}

<p-toast />
<app-unauthorized-dialog />
<div
  class="flex flex-col-reverse w-full h-svh xl:flex-row xl:p-gap xl:min-h-svh xl:h-full"
>
  <lib-nav />
  @defer {
    <div
      class="w-full overflow-y-auto p-4 xl:pl-gap xl:p-0 xl:overflow-y-visible"
    >
      <router-outlet />

      <div class="mt-4">
        <lib-footer />
      </div>
    </div>
  }
</div>
