// libs/admin-dashboard/core/domain/src/lib/nav.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router';
import Toolbar from 'primevue/toolbar';
import Button from 'primevue/button';
import Divider from 'primevue/divider';
import { useCoreStore } from '@e-commerce/admin-dashboard/core/data-access';
import { useAuthService } from '@e-commerce/admin-dashboard/auth/api';

const store = useCoreStore();
const authService = useAuthService();
</script>

<template>
  <div
    class="w-full flex items-center sticky bottom-0 left-0 right-0 xl:hidden"
  >
    <Toolbar class="bg-content-background border-none w-full">
      <template #center>
        <div
          class="mx-auto max-w-lg w-full flex items-center justify-evenly gap-4"
        >
          <Button
            size="large"
            text
            icon="pi pi-bars"
            class="text-muted-color h-10 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
          />
          <RouterLink
            to="/books/list"
            active-class="bg-surface-50 dark:bg-surface-800 rounded-base"
            class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700 cursorpointer"
          >
            <i class="pi pi-book"></i>
          </RouterLink>
          <RouterLink
            to="/"
            active-class="bg-surface-50 dark:bg-surface-800 rounded-base"
            class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700 cursorpointer"
          >
            <i class="pi pi-home"></i>
          </RouterLink>

          <RouterLink
            to="/account"
            active-class="bg-surface-50 dark:bg-surface-800 rounded-base"
            class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700 cursorpointer"
          >
            <i class="pi pi-user"></i>
          </RouterLink>
        </div>
      </template>
    </Toolbar>
  </div>

  <div class="max-w-80">
    <aside
      :class="[
        store.isExpanded ? 'w-80' : 'w-14',
        'transition-[width] duration-300 ease-in-out hidden justify-between gap-4 xl:h-content px-2 py-4 bg-content-background xl:sticky z-[501] top-4 flex-col rounded-base xl:flex',
      ]"
    >
      <nav class="h-content flex flex-col justify-between">
        <div class="flex flex-col">
          <div class="h-9 flex items-center justify-center">
            <RouterLink
              to="/"
              v-if="store.shouldLabelBeShowed"
              class="items-center justify-center"
            >
              <span class="font-bold text-primary">Story</span>
              <span class="uppercase text-muted-color">Stash</span>
            </RouterLink>

            <RouterLink
              v-if="!store.shouldLabelBeShowed"
              to="/"
              active-class="bg-surface-50 dark:bg-surface-800 rounded-base"
              class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
            >
              <i class="pi pi-home"></i>
            </RouterLink>
          </div>
          <Divider />
          <ul class="flex flex-col">
            <RouterLink
              to="/books"
              activeClass="bg-surface-50 dark:bg-surface-800"
              class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700 cursorpointer"
            >
              <i class="pi pi-book"></i>
              <span v-if="store.isExpanded">Books</span>
            </RouterLink>
          </ul>
        </div>

        <div class="flex flex-col gap-2">
          <button
            class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
            @click="authService.logout"
          >
            <i class="pi pi-sign-out"></i>
            <span v-if="store.isExpanded">Log out</span>
          </button>
          <Divider />
          <button
            class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
            @click="store.toggleTheme"
          >
            <i v-if="store.isDark" class="pi pi-moon"></i>
            <i v-if="!store.isDark" class="pi pi-sun"></i>
            <span v-if="store.isExpanded">
              {{ store.isDark ? 'Dark' : 'Light' }}
            </span>
          </button>
          <button
            class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
            @click="store.toggleExpandCollapse"
          >
            <i v-if="store.isExpanded" class="pi pi-arrow-left"></i>
            <i v-if="!store.isExpanded" class="pi pi-arrow-right"></i>
            <span>Collapse</span>
          </button>
        </div>
      </nav>
    </aside>
  </div>
</template>

// libs/client-web/core/feature/nav/src/lib/nav.component.ts
import {
  animate,
  state,
  style,
  transition,
  trigger,
} from '@angular/animations';
import { NgTemplateOutlet } from '@angular/common';
import {
  afterNextRender,
  Component,
  inject,
  OnDestroy,
  signal,
} from '@angular/core';
import { toObservable, toSignal } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import {
  NavigationEnd,
  Router,
  RouterLink,
  RouterLinkActive,
} from '@angular/router';
import { AuthService } from '@e-commerce/client-web/auth/api';
import { CartSidebarComponent } from '@e-commerce/client-web/cart/feature/cart-sidebar';
import {
  APP_LOCAL_STORAGE_KEYS_TOKEN,
  APP_ROUTE_PATHS_TOKEN,
  APP_ROUTES_FEATURE,
} from '@e-commerce/client-web/shared/app-config';
import { Category } from '@e-commerce/shared/api-models';
import {
  DrawerLeftDirective,
  NavButtonDirective,
} from '@e-commerce/client-web/shared/utils';
import { ButtonModule } from 'primeng/button';
import { DividerModule } from 'primeng/divider';
import { MenuModule } from 'primeng/menu';
import { ToolbarModule } from 'primeng/toolbar';
import { debounce, filter, map, of, timer } from 'rxjs';
import { ThemeService } from '@e-commerce/client-web/core/data-access';
import { CategoryStore } from '@e-commerce/client-web/shared/data-access/stores';
import { DrawerModule } from 'primeng/drawer';
import { GetNamePipe } from './pipes/get-name.pipe';

@Component({
  selector: 'lib-nav',
  standalone: true,
  imports: [
    DividerModule,
    ButtonModule,
    MenuModule,
    RouterLink,
    FormsModule,
    RouterLinkActive,
    DrawerModule,
    NgTemplateOutlet,
    ToolbarModule,
    NavButtonDirective,
    CartSidebarComponent,
    DrawerLeftDirective,
    GetNamePipe,
  ],
  providers: [ThemeService],
  templateUrl: './nav.component.html',
  animations: [
    trigger('slideInOut', [
      state(
        'in',
        style({
          width: '20rem',
        }),
      ),
      state(
        'out',
        style({
          width: '3.5rem',
        }),
      ),
      transition('in <=> out', [animate('300ms ease-in-out')]),
    ]),
  ],
})
export class NavComponent implements OnDestroy {
  #themeService = inject(ThemeService);
  #categoriesStore = inject(CategoryStore);
  #authService = inject(AuthService);
  #appLocalStorageKeys = inject(APP_LOCAL_STORAGE_KEYS_TOKEN);
  #appRoutePaths = inject(APP_ROUTE_PATHS_TOKEN);

  #appRouteFeatures = APP_ROUTES_FEATURE;

  isAuthenticated = this.#authService.isAuthenticated;
  categories = this.#categoriesStore.categories;
  isMobileDrawerOpened = signal(false);
  isExpanded = signal(true);
  isLabelShowed = toSignal(
    toObservable(this.isExpanded).pipe(
      debounce((isExpanded) => (isExpanded ? timer(150) : of({}))),
    ),
    { initialValue: true },
  );
  isDark = this.#themeService.isDark;

  urls = signal({
    home: this.#appRoutePaths.HOME(),
    books: this.#appRoutePaths.BOOKS(),
    orders: this.#appRoutePaths.ORDERS(),
    login: this.#appRoutePaths.LOGIN(),
    register: this.#appRoutePaths.REGISTER(),
    favouriteBooksList: this.#appRoutePaths.FAVOURITE_BOOKS_LIST(),
  }).asReadonly();

  resizeObserver = signal<ResizeObserver | null>(null);
  shouldRestoreExpanded = signal(false);

  constructor() {
    afterNextRender(() => {
      const isExpanded = localStorage.getItem(
        this.#appLocalStorageKeys.IS_EXPANDED,
      );

      if (isExpanded) {
        this.isExpanded.set(JSON.parse(isExpanded));
      }

      const mediaQueryList = matchMedia('(min-width: 1280px)');

      this.resizeObserver.set(
        new ResizeObserver(() => {
          if (mediaQueryList.matches && this.shouldRestoreExpanded()) {
            const isExpanded = JSON.parse(
              localStorage.getItem(this.#appLocalStorageKeys.IS_EXPANDED) ||
                'false',
            );

            this.isExpanded.set(isExpanded);
            this.shouldRestoreExpanded.set(false);
          } else if (!mediaQueryList.matches) {
            this.isExpanded.set(true);
            this.shouldRestoreExpanded.set(true);
          }
        }),
      );

      this.resizeObserver()?.observe(document.body);
    });
  }

  timer: any;

  ngOnDestroy() {
    this.resizeObserver()?.unobserve(document.body);
  }

  stringifyCategory(category: Category) {
    return JSON.stringify(category);
  }

  isAccountRouteActive = toSignal(
    inject(Router).events.pipe(
      filter((events) => events instanceof NavigationEnd),
      map((event) => event.url.includes(this.#appRouteFeatures.ACCOUNT.BASE)),
    ),
  );

  menuItems = signal([
    {
      label: 'Orders',
      icon: 'pi pi-book',
      routerLink: this.#appRoutePaths.ORDERS(),
      routerLinkActive: 'bg-surface-100 dark:bg-surface-700 rounded-base',
    },
    {
      label: 'Information',
      icon: 'pi pi-cog',
      routerLink: this.#appRoutePaths.INFORMATION(),
      routerLinkActive: 'bg-surface-100 dark:bg-surface-700 rounded-base',
    },
    {
      label: 'Favourite books',
      icon: 'pi pi-heart',
      routerLink: this.#appRoutePaths.FAVOURITE_BOOKS_LIST(),
      routerLinkActive: 'bg-surface-100 dark:bg-surface-700 rounded-base',
    },
  ]);

  toggleDarkMode() {
    this.#themeService.toggleDarkMode();
  }

  toggleMobileDrawer() {
    this.isMobileDrawerOpened.update((isOpen) => !isOpen);
  }

  expandCollapseNavigation() {
    this.isExpanded.update((isExpanded) => !isExpanded);
    localStorage.setItem(
      this.#appLocalStorageKeys.IS_EXPANDED,
      JSON.stringify(this.isExpanded()),
    );
  }

  logout() {
    this.#authService.logout();
  }

  closeMobileDrawer() {
    this.isMobileDrawerOpened.set(false);
  }
}

<div class="w-full flex items-center sticky bottom-0 left-0 right-0 xl:hidden">
  <p-toolbar class="w-full" styleClass="rounded-t-base mx-auto">
    <div class="mx-auto max-w-lg w-full flex items-center justify-evenly gap-4">
      <p-button
        libNavButton
        size="large"
        icon="pi pi-bars"
        (onClick)="toggleMobileDrawer()"
      />
      <p-button
        libNavButton
        size="large"
        [routerLink]="urls().books"
        routerLinkActive="bg-surface-50 dark:bg-surface-800 rounded-base"
        [queryParams]="null"
        [state]="{ clearFilters: true }"
        icon="pi pi-search"
      />
      <p-button
        libNavButton
        size="large"
        [routerLink]="urls().home"
        routerLinkActive="bg-surface-50 dark:bg-surface-800 rounded-base"
        icon="pi pi-home"
      />
      <p-button
        libNavButton
        size="large"
        [routerLink]="urls().orders"
        icon="pi pi-user"
      />
      <lib-cart-sidebar />
    </div>
  </p-toolbar>
</div>

<p-drawer libDrawerLeft [(visible)]="isMobileDrawerOpened">
  <p-header>
    <ng-container [ngTemplateOutlet]="logo" />
  </p-header>
  <div class="flex flex-col">
    <ng-container [ngTemplateOutlet]="links" />
  </div>
</p-drawer>

<aside
  class="hidden justify-between gap-4 xl:h-content px-2 py-4 bg-content-background xl:sticky z-[1001] top-4 flex-col rounded-base xl:flex"
  [@slideInOut]="isExpanded() ? 'in' : 'out'"
>
  <nav class="h-content flex flex-col justify-between">
    <div class="flex flex-col">
      <div class="h-9 flex items-center justify-center">
        @if (isLabelShowed()) {
          <ng-container [ngTemplateOutlet]="logo" />
        } @else {
          <a
            [routerLink]="urls().home"
            routerLinkActive="bg-surface-50 dark:bg-surface-800 rounded-base"
            class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
          >
            <i class="pi pi-home"></i>
          </a>
        }
      </div>
      <p-divider />
      <ul class="flex flex-col">
        <a
          [routerLink]="urls().books"
          routerLinkActive="bg-surface-50 dark:bg-surface-800"
          class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
          [queryParams]="null"
          [state]="{ clearFilters: true }"
        >
          <i class="pi pi-search"></i>
          @if (isLabelShowed()) {
            <span>Browse</span>
          }
        </a>
        <ng-container [ngTemplateOutlet]="links" />
      </ul>
    </div>

    <div class="flex flex-col">
      <lib-cart-sidebar [isLabelShowed]="isLabelShowed()" />
      @if (isAuthenticated()) {
        <a
          [routerLink]="urls().favouriteBooksList"
          class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
        >
          <i class="pi pi-heart"></i>
          @if (isLabelShowed()) {
            <span>Favourite books</span>
          }
        </a>
        <a
          [routerLink]="urls().orders"
          class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
        >
          <i class="pi pi-user"></i>
          @if (isLabelShowed()) {
            <span>Account</span>
          }
        </a>
        <button
          (click)="logout()"
          class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
        >
          <i class="pi pi-sign-in"></i>
          @if (isLabelShowed()) {
            <span>Log out</span>
          }
        </button>
      } @else {
        <a
          [routerLink]="urls().login"
          routerLinkActive="bg-surface-100 dark:bg-surface-700"
          class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
        >
          <i class="pi pi-sign-in"></i>
          @if (isLabelShowed()) {
            <span>Log in</span>
          }
        </a>
        <a
          [routerLink]="urls().register"
          routerLinkActive="bg-surface-100 dark:bg-surface-700"
          class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
        >
          <i class="pi pi-user-plus"></i>
          @if (isLabelShowed()) {
            <span>Register</span>
          }
        </a>
      }
      <p-divider />
      <div class="flex flex-col gap-2">
        <button
          (click)="toggleDarkMode()"
          class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
        >
          @if (isDark()) {
            <i class="pi pi-moon"></i>
          } @else {
            <i class="pi pi-sun"></i>
          }
          @if (isLabelShowed()) {
            <span>{{ isDark() ? 'Dark' : 'Light' }}</span>
          }
        </button>
        <button
          (click)="expandCollapseNavigation()"
          class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
        >
          @if (isExpanded()) {
            <i class="pi pi-arrow-left"></i>
          } @else {
            <i class="pi pi-arrow-right"></i>
          }
          @if (isLabelShowed()) {
            <span>Collapse</span>
          }
        </button>
      </div>
    </div>
  </nav>
</aside>

<ng-template #logo>
  <a
    [routerLink]="urls().home"
    [queryParams]="null"
    class="text-xl no-underline flex items-center justify-center"
  >
    <span class="font-bold text-primary">Story</span>
    <span class="uppercase text-muted-color">Stash</span>
  </a>
</ng-template>

<ng-template #links>
  @if (isAccountRouteActive()) {
    @for (menuItem of menuItems(); track menuItem.label) {
      <a
        (click)="closeMobileDrawer()"
        [routerLink]="menuItem.routerLink"
        routerLinkActive="bg-surface-100 dark:bg-surface-700"
        class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
      >
        <i [class]="menuItem.icon"></i>
        @if (isLabelShowed()) {
          <span>{{ menuItem.label }}</span>
        }
      </a>
    }
  } @else {
    @for (category of categories(); track category.id) {
      <a
        (click)="closeMobileDrawer()"
        [routerLink]="urls().books"
        [queryParams]="{ categories: category.name }"
        class="text-muted-color px-3 h-10 flex items-center gap-4 !rounded-base overflow-hidden hover:bg-surface-100 hover:dark:bg-surface-700"
        [state]="{ clearFilters: true }"
      >
        <span>
          {{ category.name | getName: isLabelShowed() }}
        </span>
      </a>
    }
  }
</ng-template>
