// apps/admin-dashboard/src/app/App.vue
<script setup lang="ts">
import { RouterView } from 'vue-router';
import { Nav } from '@e-commerce/admin-dashboard/core/domain';
import Toast from 'primevue/toast';
</script>

<template>
  <Toast />
  <div
    class="flex flex-col-reverse w-full h-svh xl:flex-row xl:p-gap xl:min-h-svh xl:h-full"
  >
    <Nav />
    <div
      class="w-full h-full overflow-y-auto p-4 xl:pl-gap xl:p-0 xl:overflow-y-visible"
    >
      <RouterView />
    </div>
  </div>
</template>

// apps/delivery-manager/src/app/app.tsx
import { Route, Routes } from 'react-router-dom';
import { DeliverManagerAuthFeatureShell } from '@e-commerce/delivery-manager/auth/feature/shell';
import { PrimeReactProvider } from 'primereact/api';
import 'primeicons/primeicons.css';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Nav } from '@e-commerce/delivery-manager/core/feature/nav';

const queryClient = new QueryClient();

export function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <PrimeReactProvider>
        <div className="flex flex-col-reverse w-full h-svh xl:flex-row xl:p-gap xl:min-h-svh xl:h-full">
          <Routes>
            <Route path="/" element={<Nav />}></Route>
            <Route path="auth/*" element={<DeliverManagerAuthFeatureShell />} />
          </Routes>
        </div>
      </PrimeReactProvider>
    </QueryClientProvider>
  );
}

export default App;
