// libs/admin-dashboard/auth/feature/shell/src/lib/shell.vue
<script setup lang="ts">
import { RouterView } from 'vue-router';
</script>

<template>
  <div class="flex flex-col-reverse gap-4 xl:grid xl:h-content xl:grid-cols-2">
    <div class="flex flex-col items-center justify-center w-full">
      <RouterView />
    </div>
    <div
      class="rounded-base overflow-hidden flex w-full h-full xl:content-end xl:h-content"
    >
      <img
        class="object-fill object-center w-full"
        src="/auth-books.jpg"
        alt="book store"
      />
    </div>
  </div>
</template>

// libs/client-web-app/auth/feature/shell/src/lib/shell/shell.component.ts
import { NgIf } from '@angular/common';
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { ButtonModule } from 'primeng/button';

@Component({
  selector: 'e-commerce-shell',
  standalone: true,
  imports: [ButtonModule, RouterOutlet, NgIf],
  template: `
    <div
      class="flex flex-column-reverse gap-3 xl:grid xl:flex-row xl:mb-0 xl:gap-0 height-content"
    >
      <div class="xl:col-6 h-full">
        <router-outlet></router-outlet>
      </div>
      <div
        class="border-round overflow-hidden flex align-items-start h-full xl:col-6 xl:justify-content-end"
      >
        <img
          class="border-round overflow-hidden object-fit-cover object-position-center w-full h-full"
          src="../../assets/auth-books.jpg"
          alt="book store"
        />
      </div>
    </div>
  `,
  styles: [
    `
      :host ::ng-deep input {
        width: 100%;
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ShellComponent {}
